### PR TITLE
(#33) View Terms By Letter for expand links

### LINKED ISSUE #33: Story: View Terms by Letter (/expand)
## As a user, I would like the option to view and browse the dictionary terms using an A-Z list and view the results from selecting a letter so that I can look at the list of terms the dictionary offers. 

> **ESTIMATE** 8

### Acceptance Criteria

```gherkin
Scenario: User appends /expand to the URL and tries to access the dictionary
    Given user appends "/expand" to the URL
    When user tries to go to this URL, system should return the "No Matches Found" page
```

```gherkin
Scenario: User selects a letter from A-Z list on dictionaries
    Given user is on the dictionary landing page or results page
    When user selects letter "A" from A-Z list
    Then the system returns user to the search results page for the search term "A" URL has "/expand"
    Then search results page displays results title "# results found for: A"
    And each result in the results listing appears as a link to the term's page
    And the audio icon and the pronunciation appear beside the term on the same line as the link
    And each result displays its full definition below the link for the term
```

```gherkin
Background:
    Given "language" is set to "es"

  Scenario: User selects a letter from A-Z list on dictionaries
    Given user is on the dictionary landing page or results page
    When user selects letter "M" from A-Z list
    Then search results page displays results title "# resultados de: M"
    And each result in the results listing appears as a link to the term's page
    And each result displays its full definition below the link for the term
```

```gherkin
 Background:
    Given "audience" is set to "HealthProfessional"
    Given "dictionaryName" is set to "Genetics"
    Given "language" is set to "en"

  Scenario: User clicks on a letter in the A-Z list for results and gets no matches found for the selected letter
    Given user is on landing Genetics Terms page
    When user selects letter "Y" from A-Z list
    Then the system returns user to the search results page for the search term "Y" URL has "/expand"
    And search results page displays No matches "No matches were found for your selected letter. Please try a new search, or click a different letter in the alphabet and browse through the list of terms that begin with that letter."
```

```gherkin
Scenario: Results /expand page metadata
    Given the user is viewing a results page based on clicking a letter like "A" in the dictionary
    Then '<meta name="robots" content="noindex" />' exists in the data for the page URL of "/expand/A"
```

```gherkin
Scenario: Results /expandir page metadata
    Given "language" is set to "es"
    Given the user is viewing a results page based on clicking a letter like "A" in the dictionary
    Then '<meta name="robots" content="noindex" />' exists in the data for the page URL of "/expandir/A"
```

### Resources:
* Web Page:* https://www.cancer.gov/publications/dictionaries/cancer-terms?expand=D

---

### Task list
- [x] Add `SearchBox` component to home page
- [x] Create results display page ( List & Item ) as `TermList` component
- [x] Fetch requested expand results from API
- [x] Ensure that "robots:noindex" is added to the /expand URLs
- [x] Build results page for "No Terms matching Letter selected" message 
- [x] Write automated tests

### Technical Notes
- More notes, or technical nuances/direction

### PR DESCRIPTION
**Pull request by seyilonge-nci**
Closes #33

Added unit tests [WIP...]

Increased coverage for unit tests

Added integration tests

Code cleanup

### CODE REVIEW

**Comment by VictoriaSunNIH** [comment]
https://github.com/NCIOCPL/glossary-app/pull/101 is ready for UX review (@mworrest , @blilianyu , @lburack ).

Please note that only letters A and M are available through mock data!

**Comment by blilianyu** [comment]
@seyilonge-nci Can you add some space between the pronunciation and the definition? It's really tight (possibly because of the margin-top: -5px on description). Can you also reduce the line-height for the terms? It seems more than prod.

Screenshot attached.

Screen Shot 2020-03-13 at 10 14 26 AM

**Comment by seyilonge-nci** [comment]
> @seyilonge-nci Can you add some space between the pronunciation and the definition? It's really tight (possibly because of the margin-top: -5px on description). Can you also reduce the line-height for the terms? It seems more than prod.
> 
> Screenshot attached.
> 
> Screen Shot 2020-03-13 at 10 14 26 AM

@blilianyu Will do.

**Comment by seyilonge-nci** [comment]
@blilianyu Updated as suggested. Please review.

**Comment by blilianyu** [comment]
@seyilonge-nci Looks good now! Passing :)

**Comment by seyilonge-nci** [comment]
Thanks @blilianyu

**Pull request merged**
