### PR TITLE
(#113) App should not maintain scroll position

### LINKED ISSUE #113: App should not maintain scroll position
### Issue description
When I select a term after performing either a search or expand, the term page loads but maintains my scroll position so that i am looking at the footer of the definition page instead of the top of the page with the definition.  This should be fixed so that we do not maintain the scroll position, and bring users to the top of the page when you click on a term.

> **ESTIMATE** 2

### Steps to reproduce the issue

1.  Go the Dictionary Landing Page on dev (while on VPN so that the terms load!)
2. Click on any letter in the expand list and view the expand results page for the selected letter
3. Scroll down the list of terms, and click on a term somewhere in the middle of the results list
4. Note that you are taken to the definition page, but scrolled to the position you were in (most of the time, you are taken to the footer of the definition page)

### What's the expected result?
I should be taken to the top of the definition page, and not the footer.

### What's the actual result?
Right now, I am taken to the footer

### PR DESCRIPTION
**Pull request by seyilonge-nci**
Closes #113

* Added `window.scrollTo` to `Definition` component
* Added unit test for scroll position

### CODE REVIEW

**Comment by seyilonge-nci** [comment]
@VictoriaSunNIH @blilianyu Please review https://react-app-dev.cancer.gov/glossary-app/pr-137

**Comment by VictoriaSunNIH** [comment]
Looks good to me!

**Comment by blilianyu** [comment]
Looks good on my end too!

**Comment by arcepaul** [comment]
@seyilonge-nci @blilianyu @VictoriaSunNIH 
Just confirming, I believe that the  scroll reset should also be added to the terms page.  For a page with a fairly long definition, scrolling to the bottom and hitting the back button, that scroll position is preserved as well.

**Comment by VictoriaSunNIH** [comment]
Good catch @arcepaul!  I only tested going forwards and not maintaining scroll, but didn't test using the back button since the back button can be wonky at times.

**Comment by seyilonge-nci** [comment]
> I have an open question as to whether scroll reset should be added to Terms page as well

True! Good catch, will add to terms page as well.

**Comment by seyilonge-nci** [comment]
@arcepaul Added scrolling to Term page as well.

**Pull request merged**
