### PR TITLE
(#110) API Failure Error Page

### LINKED ISSUE #110: Story: Create Error Page for when API Fails
## As a user, I need to encounter an error page when a call to the API fails.

> **ESTIMATE** XX

### Acceptance Criteria

```gherkin
Scenario: User encounters an error page when API fails
  Given user is navigating to any page within the dictionary app
   And the API is not returning data
  When user loads the page
    Then  the user gets an error page that reads "An error occurred. Please try again later."
```
```gherkin
Scenario: User encounters an error page when API fails in Spanish
  Given the language is set to ES
  Given user is navigating to the Spanish dictionary landing page
  And the API is not returning data
  When user loads the page 
    Then  the user gets an error page that reads "Se produjo un error. Por favor, vuelva a intentar más tarde."
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: https://publicis.invisionapp.com/share/HZVRID6RSJ7#/413568379_DICTIONARY_OF_CANCER_TERMS_RESULTS_Error_-_Desktop_HD_-_1441_--_1025
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

### PR DESCRIPTION
**Pull request by seyilonge-nci**
Closes #110

* Added integration tests for API error page
* Fixed failing integration tests
* Update customFetch to add actual error message
* Update to setUpProxy to return results for not found directory rather than 404
* Added missing piece from previous rebase conflict
* Moved termCount call to IntroText
* Fixed integration tests for API failure, Site-wide language toggle, and added missing initialize params for test
* Updated and added mock file for MetaTagInUnrelatedApp.feature
* Removed spinner for IntroText component
* Bumped up axios timeout, added unit tests for customFetch

### CODE REVIEW

**Comment by seyilonge-nci** [comment]
@VictoriaSunNIH @lburack @blilianyu Please review 

In order to test please follow the instructions below
1. Connect the the NIH VPN and then visit https://react-app-dev.cancer.gov/glossary-app/pr-119
2. Once page is loaded disconnect from the NIH VPN
3. Click on any of the expand links

A call would be made to the api residing inside the NIH network. It would eventually timeout since it can't connect and then display the page.

**Comment by blilianyu** [comment]
@seyilonge-nci Could you replace the loader for term count with {{term_count}} instead so we don't have 2 loaders going?

**Comment by seyilonge-nci** [comment]
> @seyilonge-nci Could you replace the loader for term count with {{term_count}} instead so we don't have 2 loaders going?

@blilianyu Done as discussed!

**Comment by blilianyu** [comment]
@seyilonge-nci Looks great! Passing UX review!

**Pull request merged**
