### PR TITLE
Hotfix/v1.2.1

### PR DESCRIPTION
**Pull request by arcepaul**
Fix for autocomplete menu detachment
  - reverted nci-dev_common back to match prod Common.css
  - scoped margin change to autocomplete input

### CODE REVIEW

**Comment by arcepaul** [comment]
@kate-mashkina @mworrest @alinai 
https://react-app-dev.cancer.gov/glossary-app/pr-235/
fixes for glossary app are now available.  Please check it out and let me know if I missed anything.

**Comment by kate-mashkina** [comment]
Could you increase spacing between H1 term title and pronunciation to match what we have in prod?
its too tight currently - https://react-app-dev.cancer.gov/glossary-app/pr-235/def/xalkori vs prod https://www.cancer.gov/publications/dictionaries/cancer-terms/def/xalkori

**Comment by alinai** [comment]
@VictoriaSunNIH, Seeing the vertical scroll bar on definition page (Test url: https://react-app-dev.cancer.gov/glossary-app/pr-235/def/b-lymphocyte). We can see it happening the first time when we type a term (with more options in the dro-down). Next time if we type the same term then the drop-down flips. On Prod Drug Dict. definition page (https://www.cancer.gov/publications/dictionaries/cancer-drug/def/a-101-topical-solution)  we see that the drop-down is not flipping the first time a term is typed but no vertical scroll bar appears on the page. Test Browser: Chrome. 
1. Refresh the page and then 
2. Bring the search bar to its lowest position so that you don't see the A-Z list 
3. Type the term

image






12:07
then type your term

**Comment by arcepaul** [comment]
Does the above issue occur on prod?

**Comment by alinai** [comment]
> Does the above issue occur on prod?

No vertical scroll bar appears on Prod

**Comment by arcepaul** [comment]
ah, ok.  This looks to me to be caused by the absence of the footer on. react app dev.  If you change the length of the page by changing the padding of the general-page-body-container, no scrollbar will appear.
Screen Shot 2021-03-26 at 12 47 22 PM

**Comment by alinai** [comment]
Should we expect to see the following issue addressed on the ODE?

image

**Comment by alinai** [comment]
When on definition page, if the placeholder text starts showing up flipped, then on typing first character it flips down, and on typing second character it flips up.This is a case when the search box is all the way at the bottom of your screen ( so the dropdown should be up ). Test url: https://react-app-dev.cancer.gov/glossary-app/pr-235/def/metastasis

**Comment by alinai** [comment]
When there is one item in the drop-down, the drop-down overlays part of the search button making the Search button look thinner. Search term "world health organization"

image

**Comment by mworrest** [comment]
I am no longer seeing the menu detachment issue.

**Comment by bryanpizzillo** [comment]
> I am no longer seeing the menu detachment issue.

@mworrest are you ok (and the answer should be yes) with the slightly "fatter" menu that overlays the button making the button seem thinner as documented in https://github.com/NCIOCPL/glossary-app/pull/235#issuecomment-808440814?

**Comment by bryanpizzillo** [comment]
> Should we expect to see the following issue addressed on the ODE?
> 
> image

This is outside the scope of this. Everyone approved the PR for https://github.com/NCIOCPL/glossary-app/pull/229, which introduced this new spacing. Please enter a change request for this, and pretty please do not make the title "Add margin after player icon".

**Comment by mworrest** [comment]
> > I am no longer seeing the menu detachment issue.
> 
> @mworrest are you ok (and the answer should be yes) with the slightly "fatter" menu that overlays the button making the button seem thinner as documented in [#235 (comment)](https://github.com/NCIOCPL/glossary-app/pull/235#issuecomment-808440814)?

I am ok with it.

**Comment by VictoriaSunNIH** [comment]
> When on definition page, if the placeholder text starts showing up flipped, then on typing first character it flips down, and on typing second character it flips up.This is a case when the search box is all the way at the bottom of your screen ( so the dropdown should be up ). Test url: https://react-app-dev.cancer.gov/glossary-app/pr-235/def/metastasis

This seems like something that was introduced that is not currently on prod.

**Review by bryanpizzillo — APPROVED** [review]

**Pull request merged**
