### PR TITLE
Ticket #226 Axios version update to fix high severity security issue warning

### LINKED ISSUE #226: Axios version update to fix high severity security issue warning
Github's dependabot is complaining that the version of axios in use opens up the app to a high severity security vulnerability. Axios version should be updated and the app retested for accuracy and functionality.

Please take note of the steps in this fix as it may have to be applied to all of the other appmodules
```
NCIOCPL/clinical-trials-search-app
NCIOCPL/drug-dictionary-app
NCIOCPL/sitewide-search-app
NCIOCPL/cgov-react-app-playground
```

Secondarily, using the results of `npm audit`, figure out what packages might need to be updated and can be without impacting the performance of the glossary app.

Screen Shot 2021-01-05 at 3 31 51 PM

### PR DESCRIPTION
**Pull request by alerosad**
Closes #226

Updated axios dependency, along with the other listed packages

npm install --save-dev resolve-url-loader@3.1.2
npm update selfsigned --depth 2
npm install axios@0.21.1
npm update ini --depth 4
npm update null --depth 4
npm update watchpack --depth 2
npm install --save-dev cypress-cucumber-preprocessor@4.0.

### CODE REVIEW

**Comment by alerosad** [comment]
I also ran: 
npm install --save-dev babel-jest@26.6.3 
npm install --save-dev webpack@5.11.1 
npm install --save-dev jest@26.6.3 

on a separate testing branch, and when I did, these updates either messed up testing/running the application or affected the performance. So I did not include these in the PR.

**Review by blairlearn — CHANGES_REQUESTED** [review]
@alerosad - The changes make sense to me, but please modify your commit comment.  The preferred format is

`(#1234) Ticket title`

Obviously, replacing `1234` with the actual ticket number and `Ticket title` with the actual title. If there are additional details needed (e.g. an explanation of why the cucumber preprocessor was also updated), add a blank line and then put the additional text on subsequent lines.

The `Closes #1234` text belongs in the PR comment, not the git commit comment.

**Comment by kate-mashkina** [comment]
I am approving this pull request from QA perspective - cypress updates appear to be in order. I am not sure if other updates, besides axios, were also required - leaving it for @arcepaul judgment

**Review by kate-mashkina — APPROVED** [review]

**Review by arcepaul — APPROVED** [review]

**Review by blairlearn — APPROVED** [review]

**Comment by alerosad** [comment]
https://react-app-dev.cancer.gov/glossary-app/pr-228/ @mworrest @blilianyu @lburack

**Comment by lburack** [comment]
@alerosad @arcepaul - is the language toggle at the top supposed to work? The dropdown on the bottom right allows me to change language though.

Functionality wise, things look to be fine. 
Some of the Spanish content is different than what is on PROD right now. Not sure if this related to the Axios updates, but noting it to make sure the correct content on PROD remains intact:
- the italics text in the search box
  - react-app: Escriba frase o palabra
  - PROD: Escriba frase o palabra clave
- text before the alphabetical letter links 
   - react-app: Navegar por letra inicial:
   - PROD: Ojear:

Screen_Shot_2021-02-02_at_5_54_01_PM

@blilianyu @mworrest

**Comment by alerosad** [comment]
> @alerosad @arcepaul - is the language toggle at the top supposed to work? The dropdown on the bottom right allows me to change language though.
> 
> Functionality wise, things look to be fine.
> Some of the Spanish content is different than what is on PROD right now. Not sure if this related to the Axios updates, but noting it to make sure the correct content on PROD remains intact:
> 
> * the italics text in the search box
>   
>   * react-app: Escriba frase o palabra
>   * PROD: Escriba frase o palabra clave
> * text before the alphabetical letter links
>   
>   * react-app: Navegar por letra inicial:
>   * PROD: Ojear:
> 
> Screen_Shot_2021-02-02_at_5_54_01_PM
> 
> @blilianyu @mworrest

Yeah in issue #208, I was told to change some of the Spanish text in order to make them grammatically correct. https://github.com/NCIOCPL/glossary-app/issues/208

And when I pull from the most recent version of develop the language toggle doesn't work for me either, not sure if it's supposed to but I never changed anything and it's never worked for me. Not sure if I'm missing something on my local computer in order to get it to function correctly.

**Comment by mworrest** [comment]
There is also the discrepancy on a term page https://react-app-dev.cancer.gov/glossary-app/pr-228/def/ablacion-con-coagulador-de-haz-de-argon

**Comment by mworrest** [comment]
Could you please add more space under the H1 on Spanish genetics dictionary so it matches the others? 
Spanish:
Screen Shot 2021-02-03 at 11 17 02 AM

English:
Screen Shot 2021-02-03 at 11 17 09 AM

**Comment by mworrest** [comment]
I think the heading on a term page be: 
Consulte el Diccionario de genética del NCI
instead of: 
Busca diccionario de genética

That would be consistent with the cancer terms dictionary.

**Comment by blairlearn** [comment]
@mworrest @blilianyu @lburack - The axios update only affects the app's ability to retrieve data.  Changes to layout and the text are out of scope for this ticket (and hopefully beyond the ability of anything axios can affect).

I noticed there's another instance of the app at https://react-app-dev.cancer.gov/glossary-app/develop.  Assuming  that parallels the `develop` branch (completed but not released), that might be a useful comparison point for visual comparisons. (e.g. new wording.)

**Pull request merged**
