### PR TITLE
(#43) Added SearchBox to term page

### LINKED ISSUE #43: Story: Term Page - Search Box Display
## As a user, I would like the option to search for another term while on a term page so I don't have to navigate back to the dictionary landing page.

> **ESTIMATE** 2

### Acceptance Criteria

```gherkin
Scenario: As a user, I would like to see an option to search when I am viewing the definition for a term
  Given the user is viewing the definition with the pretty url "metastatic"
  Then heading "Search NCI's Dictionary of Cancer Terms" appears
  Then search options for "Starts with" and "Contains" appears
  Then "keywords" search box appears
  Then search button appears beside search box with "Search"
  Then "Browse:" appears with A-Z List of Links beside it
  And user submits their search 
  Then the system returns users to the search results page for the search term
```

```gherkin
Scenario: As a user, I would like to see an option to browse the A-Z list when I am viewing the definition for a term
  Given the user is viewing the definition with the pretty url "metastatic"
  Then heading "Search NCI's Dictionary of Cancer Terms" appears
  Then search options for "Starts with" and "Contains" appears
  Then "keywords" search box with "Escribir frase o palabra" appears
  Then search button appears beside search box with "Search"
  Then "Browse:" appears with A-Z List of Links beside it
  When user clicks a letter in the A-Z list 
  Then the system returns users to the search results page for the letter
```

```gherkin
Background:
    Given "language" is set to "es"
Scenario: As a user, I would like to see an option to search when I am viewing the definition for a term in Spanish
  Given the user is viewing the definition with the pretty url "metastasico"
  Then heading "Buscar en el Diccionario de cáncer" appears
  Then search options for "Empieza con" and "Contiene" appears
  Then "keywords" search box appears
  Then search button appears beside search box with "Buscar"
  Then "Navegar por letra inicial:" appears with A-Z List of Links beside it
  And user submits their search 
  Then the system returns users to the search results page for the search term
```

```gherkin
Background:
    Given "language" is set to "es"
Scenario: As a user, I would like to see an option to browse the A-Z list when I am viewing the definition for a term in Spanish
Given the user is viewing the definition with the pretty url "metastasico"
  Then heading "Buscar en el Diccionario de cáncer" appears
  Then search options for "Empieza con" and "Contiene" appears
  Then "keywords" search box appears
  Then search button appears beside search box with "Buscar"
  Then "Navegar por letra inicial:" appears with A-Z List of Links beside it
  When user clicks a letter in the A-Z list 
  Then the system returns users to the search results page for the letter
```
```gherkin
Scenario: User can execute search by hitting the Enter key 
  Given user is on landing Cancer Terms page 
  When user starts typing “cancer”  in the search bar 
  Then placeholder text disappears  
  When user hits Enter key
    Then Search is executed  
  Then the system returns users to the search results page for the search term (URL has /search)
```

```gherkin
Scenario: User can execute search by hitting the Enter key 
  Given user is on landing Cancer Terms page 
    And user selects "Contains"
    And user types search keywords in the search bar 
  Then placeholder text disappears  
  When user hits Enter key
    Then Search is executed  
  Then the system returns users to the search results page for the search term (URL has /search)
```

```gherkin
Background
  Given "language" is set to "es"
Scenario: User can execute search by hitting the Enter key 
  Given user is on Spanish landing Cancer Terms page 
    And user selects "Contiene"
    And user types search keywords in the search bar 
  Then placeholder text disappears  
  When user hits Enter key
    Then Search is executed  
  Then the system returns users to the search results page for the search term (URL has /buscar)
```

### Resources:
* Mockups: https://publicis.invisionapp.com/share/HZVRID6RSJ7#/screens/402838500
* Web Page: https://www.cancer.gov/publications/dictionaries/cancer-terms/def/metastasis

### Notes
* Since we will have multiple titles based on whichever dictionary is being viewed, and Spanish is complicated we will need to make it so that we pass in the text above the search bar to the initialization of the app. 
---

### Prerequisites
- [x] Basic Term Page view has been built (#15)
- [x] Basic Search Box has been built (#76)
- [x] A-Z list has been built (#76)
- [x] Starts With and Contains buttons have been built (first round - no autosuggest) (#76)

### Tasks
- [ ] Add SearchBox to Basic Term Page (#86)
- [ ] Add integration tests

### Technical Notes
- More notes, or technical nuances/direction

### LINKED ISSUE #86: Add SearchBox to Basic Term Page
Include `SearchBox` component on Basic Term page

**Parent Issue:** #43 

### Sub-Tasks
- [x] Add `SearchBox` component
- [x] Update tests for Basic Term page
- [x] Add title to `SearchBox` component (would only show in Basic Term page display context)

### Notes

### PR DESCRIPTION
**Pull request by seyilonge-nci**
Closes #43

Added SearchBox to term page, added search box title and showTitle prop to SearchBox, style updates
Closes #86

Added integration tests

Removed unwanted file

### CODE REVIEW

**Comment by seyilonge-nci** [comment]
@VictoriaSunNIH @lburack 
Searchbox on term page for review at: https://react-app-dev.cancer.gov/glossary-app/pr-91/def/445043

**Comment by lburack** [comment]
@seyilonge-nci — some of the styling looks different than the design comp. Tagging @mworrest and @blilianyu on this as well for their guidance. 

Searchbox on term page: https://react-app-dev.cancer.gov/glossary-app/pr-91/def/445043
Design comp: https://publicis.invisionapp.com/share/HZVRID6RSJ7#/screens/402835214

**Comment by mworrest** [comment]
A-Z is using the wrong color and the radio buttons aren't the ones from CTS.

**Comment by seyilonge-nci** [comment]
> A-Z is using the wrong color and the radio buttons aren't the ones from CTS.
@mworrest 
Thanks Michelle, making the updates...

**Comment by seyilonge-nci** [comment]
> A-Z is using the wrong color (should be #2B7BBA) and the radio buttons aren't the ones from CTS.
> @lburack shouldn't the heading 'Search NCI's Dictionary of Cancer Terms' be an H6?

Updated as requested

**Comment by blilianyu** [comment]
@seyilonge-nci  Looks good! Passing :)

**Pull request merged**
