### PR TITLE
(#28) Pronunciation block on Definition page

### PR DESCRIPTION
**Pull request by arcepaul**
Front end for ticket #28 
- implemented render of pronunciation key and audio on definition page
- added unit and integration tests

### CODE REVIEW

**Comment by arcepaul** [comment]
@VictoriaSunNIH @lburack 
Test server available at: https://react-app-dev.cancer.gov/glossary-app/pr-89/def/445043

**Comment by VictoriaSunNIH** [comment]
Tagging @mworrest and @blilianyu to take a look at the audio icon on the term page as well!

**Comment by mworrest** [comment]
Play and pause icons look squished. Pause does not look like the correct icon that @blilianyu   created. See comps for comparison: https://publicis.invisionapp.com/share/HZVRID6RSJ7

**Comment by blilianyu** [comment]
@arcepaul Attached is the pause icon! https://lion.box.com/s/5soqjjbnvoapbp0ifxk9bbr8td44mmvk

**Comment by arcepaul** [comment]
@blilianyu @mworrest 
icon updated

**Comment by blilianyu** [comment]
@arcepaul per the acceptance criteria, @mworrest and I would like the hover play state to be removed. On hover, it should still be the play icon.

**Pull request merged**
