### PR TITLE
(#237) fix for jumping automenu

### PR DESCRIPTION
**Pull request by arcepaul**
The position check was being called 3 times for each render.  reduced it to one check

### CODE REVIEW

**Comment by arcepaul** [comment]
https://react-app-dev.cancer.gov/glossary-app/pr-239/def/aat-deficiency
@mworrest @blilianyu @VictoriaSunNIH @alinai @kate-mashkina 
Ok, fix is up and ready for testing.  Please also use the trick to add some padding to the body of the page container to avoid that extra scrollbar (non-issue) from popping up.

**Comment by mworrest** [comment]
I no longer see the autosuggest menu alternating from above and below the input box when typing a term.

**Comment by arcepaul** [comment]
@bryanpizzillo @kate-mashkina 
The shell index.html and its css had to be updated because in cypress the menu would overlap the header and parts of the menu would be hidden, causing cypress to freak out and fail the integration tests.  So I updated the shell with a floated element fix and added a faux footer to help with testing.

**Review by bryanpizzillo — APPROVED** [review]
Looks like code!

**Comment by kate-mashkina** [comment]
The autosuggest still alternates  , but now at the top of a page - when you continue typing letters in the box
Screen Shot 2021-03-29 at 4 43 57 PM

Screen Shot 2021-03-29 at 4 43 52 PM

**Comment by arcepaul** [comment]
Think I found the underlying problem.  When the menu switches to above the input, the calculation for if the menu fits BELOW the input box changes.  Updated code to reflect that new calculation conditional on whether or not the menu anchor is bottom up vs. top down

**Comment by VictoriaSunNIH** [comment]
This looks good to me!

**Review by bryanpizzillo — APPROVED** [review]

**Pull request merged**
