### PR TITLE
(#29) Media display on term definition page

### PR DESCRIPTION
**Pull request by arcepaul**
- create component for cgov image
- create component for cgov video
- unit tests and integration test added
- updates to integration tests for Definition for better coverage and missing spanish text for header

### CODE REVIEW

**Comment by arcepaul** [comment]
@kate-mashkina here are the new branches created for the media feature to rebase your media-tests branch with

**Comment by bryanpizzillo** [comment]
@VictoriaSunNIH and/or @lburack
https://react-app-dev.cancer.gov/glossary-app/pr-85/def/445043
(As of 9:08 the API is down)

**Comment by VictoriaSunNIH** [comment]
@arcepaul , @bryanpizzillo - Looking at this, More Information label should not be showing unless there are related links (a different story).  That label shouldn't display if there is only media being shown (example: https://www.cancer.gov/publications/dictionaries/cancer-terms/def/philadelphia-chromosome)

**Comment by arcepaul** [comment]
@VictoriaSunNIH @lburack - In the case of metastatic, there are related links but that piece hasn't been built out yet.  So the more information appears because related links are present in the response.

**Pull request merged**
